<a href="https://colab.research.google.com/github/JefNtungila/DS-Unit-2-Regression-1/blob/master/Assignment_logistic_regression_categorical_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
train_features = pd.read_csv('https://drive.google.com/uc?export=download&id=14ULvX0uOgftTB2s97uS8lIx1nHGQIB0P')
train_labels = pd.read_csv('https://drive.google.com/uc?export=download&id=1r441wLr7gKGHGLyPpKauvCuUOU556S2f')
test_features = pd.read_csv('https://drive.google.com/uc?export=download&id=1wvsYl9hbRbZuIuoaLWCsW_kbcxCdocHz')
sample_submission = pd.read_csv('https://drive.google.com/uc?export=download&id=1kfJewnmhowpUo381oSn3XqsQ6Eto23XV')
train_features.shape, train_labels.shape, test_features.shape, sample_submission.shape

((59400, 40), (59400, 2), (14358, 40), (14358, 2))

##Baseline

In [0]:
y_train = train_labels['status_group']
y_train.value_counts(normalize=True)

functional                 0.543081
non functional             0.384242
functional needs repair    0.072677
Name: status_group, dtype: float64

In [0]:
majority_class = y_train.mode()[0]
majority_class

'functional'

In [0]:
y_pred = [majority_class] * len(y_train) #constantly predicting the most likely outcome

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_pred)

0.543080808080808

##Cleaning data

In [0]:
train_features.columns.values

array(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code',
       'lga', 'ward', 'population', 'public_meeting', 'recorded_by',
       'scheme_management', 'scheme_name', 'permit', 'construction_year',
       'extraction_type', 'extraction_type_group',
       'extraction_type_class', 'management', 'management_group',
       'payment', 'payment_type', 'water_quality', 'quality_group',
       'quantity', 'quantity_group', 'source', 'source_type',
       'source_class', 'waterpoint_type', 'waterpoint_type_group'],
      dtype=object)

In [0]:
train_features.isnull().sum()

id                           0
amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
dtype: int64

In [0]:
train_features[['funder','installer','subvillage','public_meeting','scheme_management','scheme_name','permit']].describe(include='all').T

                   count unique                     top   freq
funder             55765   1897  Government Of Tanzania   9084
installer          55745   2145                     DWE  17402
subvillage         59029  19287                Madukani    508
public_meeting     56066      2                    True  51011
scheme_management  55523     12                     VWC  36793
scheme_name        31234   2696                       K    682
permit             56344      2                    True  38852

In [0]:
df.fillna(df.mean(), inplace=True)

In [0]:

train_features[['funder','installer','subvillage','public_meeting','scheme_management','scheme_name','permit']].fillna(
train_features[['funder','installer','subvillage','public_meeting','scheme_management','scheme_name','permit']].mode())

                         funder  ... permit
0                         Roman  ...  False
1                       Grumeti  ...   True
2                  Lottery Club  ...   True
3                        Unicef  ...   True
4                   Action In A  ...   True
5           Mkinga Distric Coun  ...   True
6                          Dwsp  ...   True
7                         Rwssp  ...   True
8                      Wateraid  ...   True
9                   Isingiro Ho  ...   True
10                      Private  ...  False
11                       Danida  ...  False
12                 World Vision  ...  False
13      Lawatefuka Water Supply  ...   True
14                        Biore  ...   True
15                        Rudep  ...  False
16                       Unicef  ...   True
17                       Unicef  ...   True
18                       Hesawa  ...   True
19                       Danida  ...   True
20                          Twe  ...  False
21                         Dwsp  ...  False
22                       Unicef  ...   True
23                          Isf  ...   True
24     African Development Bank  ...   True
25       Government Of Tanzania  ...   True
26                       Sobodo  ...  False
27                       Hesawa  ...   True
28       Government Of Tanzania  ...   True
29      Lawatefuka Water Supply  ...   True
...                         ...  ...    ...
59370                       NaN  ...  False
59371               Netherlands  ...  False
59372                       Tlc  ...   True
59373                     Rudep  ...   True
59374                     Rwssp  ...  False
59375    Government Of Tanzania  ...   True
59376                       NaN  ...    NaN
59377    Government Of Tanzania  ...  False
59378                        Rc  ...   True
59379                        Do  ...   True
59380                     Roman  ...  False
59381       Mkinga Distric Coun  ...   True
59382                 Ces(gmbh)  ...   True
59383                World Bank  ...   True
59384                   Concern  ...  False
59385                     Jaica  ...   True
59386                       Adb  ...  False
59387                         0  ...  False
59388                     Kidep  ...   True
59389                        Co  ...  False
59390                     Rudep  ...  False
59391    Government Of Tanzania  ...   True
59392    Government Of Tanzania  ...   True
59393                   Private  ...  False
59394                World Bank  ...   True
59395           Germany Republi  ...   True
59396               Cefa-njombe  ...   True
59397                       NaN  ...  False
59398                     Malec  ...   True
59399                World Bank  ...   True

[59400 rows x 7 columns]

In [0]:
train_features.isnull().sum()

id                           0
amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
dtype: int64

In [0]:
train_features.head(15).T

                                            0   ...                       14
id                                       69572  ...                    53752
amount_tsh                                6000  ...                        0
date_recorded                       2011-03-14  ...               2012-10-20
funder                                   Roman  ...                    Biore
gps_height                                1390  ...                        0
installer                                Roman  ...                   WEDECO
longitude                              34.9381  ...                  34.3641
latitude                              -9.85632  ...                 -3.62933
wpt_name                                  none  ...                Mwabasabi
num_private                                  0  ...                        0
basin                               Lake Nyasa  ...                 Internal
subvillage                            Mnyusi B  ...                Mwabasabi
region                                  Iringa  ...                Shinyanga
region_code                                 11  ...                       17
district_code                                5  ...                        6
lga                                     Ludewa  ...                    Meatu
ward                                  Mundindi  ...                    Nkoma
population                                 109  ...                        0
public_meeting                            True  ...                     True
recorded_by            GeoData Consultants Ltd  ...  GeoData Consultants Ltd
scheme_management                          VWC  ...                      WUG
scheme_name                              Roman  ...                     None
permit                                   False  ...                     True
construction_year                         1999  ...                        0
extraction_type                        gravity  ...              nira/tanira
extraction_type_group                  gravity  ...              nira/tanira
extraction_type_class                  gravity  ...                 handpump
management                                 vwc  ...                      wug
management_group                    user-group  ...               user-group
payment                           pay annually  ...                never pay
payment_type                          annually  ...                never pay
water_quality                             soft  ...                     soft
quality_group                             good  ...                     good
quantity                                enough  ...                   enough
quantity_group                          enough  ...                   enough
source                                  spring  ...             shallow well
source_type                             spring  ...             shallow well
source_class                       groundwater  ...              groundwater
waterpoint_type             communal standpipe  ...                hand pump
waterpoint_type_group       communal standpipe  ...                hand pump

[40 rows x 15 columns]