In [2]:
import pandas as pd

columns = ['Year','Incumbent Party Candidate','Other Candidate','Incumbent Party Vote Share']

data = [[1952,"Stevenson","Eisenhower",44.6],
        [1956,"Eisenhower","Stevenson",57.76],
        [1960,"Nixon","Kennedy",49.91],
        [1964,"Johnson","Goldwater",61.34],
        [1968,"Humphrey","Nixon",49.60],
        [1972,"Nixon","McGovern",61.79],
        [1976,"Ford","Carter",48.95],
        [1980,"Carter","Reagan",44.70],
        [1984,"Reagan","Mondale",59.17],
        [1988,"Bush, Sr.","Dukakis",53.94],
        [1992,"Bush, Sr.","Clinton",46.55],
        [1996,"Clinton","Dole",54.74],
        [2000,"Gore","Bush, Jr.",50.27],
        [2004,"Bush, Jr.","Kerry",51.24],
        [2008,"McCain","Obama",46.32],
        [2012,"Obama","Romney",52.00], 
        [2016,"Clinton","Trump",48.2]]
        
votes = pd.DataFrame(data=data, columns=columns)

columns = ['Year','Average Recent Growth in Personal Incomes']

data = [[1952,2.40],
        [1956,2.89],
        [1960, .85],
        [1964,4.21],
        [1968,3.02],
        [1972,3.62],
        [1976,1.08],
        [1980,-.39],
        [1984,3.86],
        [1988,2.27],
        [1992, .38],
        [1996,1.04],
        [2000,2.36],
        [2004,1.72],
        [2008, .10],
        [2012, .95], 
        [2016, .10]]
        
growth = pd.DataFrame(data=data, columns=columns)

"""
Fatalities denotes the cumulative number of American military
fatalities per millions of US population the in Korea, Vietnam,
Iraq and Afghanistan wars during the presidential terms
preceding the 1952, 1964, 1968, 1976 and 2004, 2008 and
2012 elections.

http://www.douglas-hibbs.com/HibbsArticles/HIBBS-PRESVOTE-SLIDES-MELBOURNE-Part1-2014-02-26.pdf
"""

columns = ['Year','US Military Fatalities per Million']

data = [[1952,190],
        [1956,  0],
        [1960,  0],
        [1964,  1],
        [1968,146],
        [1972,  0],
        [1976,  2],
        [1980,  0],
        [1984,  0],
        [1988,  0],
        [1992,  0],
        [1996,  0],
        [2000,  0],
        [2004,  4],
        [2008, 14],
        [2012,  5], 
        [2016,  5]]
        
deaths = pd.DataFrame(data=data, columns=columns)

df = votes.merge(growth).merge(deaths)

In [3]:
df.head()

,Year,Incumbent Party Candidate,Other Candidate,Incumbent Party Vote Share,Average Recent Growth in Personal Incomes,US Military Fatalities per Million
0,1952,Stevenson,Eisenhower,44.60,2.40,190
1,1956,Eisenhower,Stevenson,57.76,2.89,0
2,1960,Nixon,Kennedy,49.91,0.85,0
3,1964,Johnson,Goldwater,61.34,4.21,1
4,1968,Humphrey,Nixon,49.60,3.02,146

In [48]:
gdpdf  = pd.read_csv('gdp.csv', header=None)
headers = gdpdf.T.iloc[1]
headers[0] = 'Year'
headers[1] = 'Quarter'
gdpdf = gdpdf.T[2:]

In [49]:
gdpdf = gdpdf.rename(columns=headers)
gdpdf['Year'] = gdpdf['Year'].astype(int)
gdpdf.head()

,Year,Quarter,Gross domestic product (GDP),Plus: Income receipts from the rest of the world,Less: Income payments to the rest of the world,Equals: Gross national product,Less: Consumption of fixed capital,Private,Government,General government,...,Addenda:,Gross domestic income (GDI)1,Average of GDP and GDI2,Gross national income3,Net domestic product,Net domestic income4,Net domestic purchases,"Gross national product, current dollars","Gross domestic income, current dollars","Average of GDP and GDI, current dollars5"
2,1947,Q2,-1.0,14.7,-10.3,-0.9,-2.3,7.9,-15.6,-16.2,...,NaN,-0.5,-0.8,-0.4,-0.9,-0.3,-0.2,4.9,5.3,5.0
3,1947,Q3,-0.8,-5.2,-13.1,-0.8,-1.4,8.1,-14.9,-15.5,...,NaN,0.5,-0.2,0.4,-0.7,0.7,-0.7,6.0,7.4,6.7
4,1947,Q4,6.4,45.1,91.8,6.5,-0.7,8.4,-14.1,-14.7,...,NaN,3.9,5.1,4.0,7.4,4.5,13.1,17.4,14.5,15.9
5,1948,Q1,6.2,24.3,-22.1,6.3,0.3,8.6,-13.1,-13.7,...,NaN,11.2,8.6,11.3,6.9,12.7,10.7,9.8,14.7,12.1
6,1948,Q2,6.8,18.8,2.1,6.9,0.5,7.9,-12.1,-12.7,...,NaN,9.6,8.2,9.7,7.6,10.8,11.5,10.8,13.6,12.1

In [77]:
def get_sum_period(y1,y2, colname, df=gdpdf):
    df[colname] = df[colname].astype(float)
    sliced = df[(y1 <= df['Year']) & (df['Year'] <= y2)]
    return sliced[colname].sum()

In [124]:
#current year and year prior
df['GDP Percent Increase'] = df['Year'].apply(lambda x: get_sum_period(x-1,x, 'Gross domestic product (GDP)', gdpdf))

In [125]:
df.corr()[['Incumbent Party Vote Share']]
#GDP is a good predictor but not better than Average Recent Growth in Personal Incomes

                                           Incumbent Party Vote Share
Year                                                        -0.219182
Incumbent Party Vote Share                                   1.000000
Average Recent Growth in Personal Incomes                    0.766281
US Military Fatalities per Million                          -0.364377
GDP Percent Increase                                         0.638171

In [103]:
from sklearn.linear_model import LinearRegression

In [159]:
parameters = df[['Average Recent Growth in Personal Incomes', 'US Military Fatalities per Million', 'GDP Percent Increase']]
y_true = df['Incumbent Party Vote Share']

model = LinearRegression().fit(parameters , y_true)

In [160]:
pred = model.predict(parameters)

In [161]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_true, pred)

1.359135629923012

In [186]:
#add more data

In [224]:
rpi_df = pd.read_csv('rpi.csv')
rpi_df['DATE'] = rpi_df['DATE'].apply(lambda x: x.split('-')[0]).astype(int)
rpi_df.head()

   DATE  DPCERL1A225NBEA
0  1930             -5.4
1  1931             -3.1
2  1932             -9.0
3  1933             -2.2
4  1934              7.1

In [261]:
def get_mean_pi(y1, y2, df=rpi_df):
    sliced = df[(y1 <= df['DATE']) & (df['DATE'] <= y2)]
    return sliced['DPCERL1A225NBEA'].mean()

In [260]:
df['Real Persnal Income'] = df['Year'].apply(lambda x: get_mean_pi(x-1,x, rpi_df))

df.corr()[['Incumbent Party Vote Share']]

                                           Incumbent Party Vote Share
Year                                                        -0.219182
Incumbent Party Vote Share                                   1.000000
Average Recent Growth in Personal Incomes                    0.766281
US Military Fatalities per Million                          -0.364377
GDP Percent Increase                                         0.638171
Real Persnal Income                                          0.723256
RPI Growth2                                                  0.723256

1.359135629923012